### ISSUE TITLE
Why my files grows when I upload?

### ISSUE THREAD

**Issue by fpcimmino** [pionl/laravel-chunk-upload#100]
When I upload one file of 93.1MB it become 2.6GB and is corrupted. Why?

**Comment by pionl** [comment]
> This should be fine, what library you are using? Probably there is an issue that the library sends incorrect chunk index or file key. I would recommend to debug the data that is coming to find a solution.

Duplicate: https://github.com/pionl/laravel-chunk-upload-example/issues/19

**Comment by pionl** [comment]
Hi can you try new version?

-- 

Fixed a bug and added a support for Laravel 7 in [v1.4.0]( https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.4.0)

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).

Thank you for your patience.
