### ISSUE TITLE
Laravel 7 FileException error

### ISSUE THREAD

**Issue by MahdiPishguy** [pionl/laravel-chunk-upload#106]
i implemented view, controller and route and now when i try to upload file i get this error:

> Symfony\Component\HttpFoundation\File\Exception\FileException: The
> file "XXXXXXXX" was not uploaded due to an unknown error. in file
> C:\xampp\htdocs\XXX\vendor\symfony\http-foundation\File\UploadedFile.php
> on line 213

and i can't fix this error:

**view**:

    <div class="form-group">
        <div class="resumable-error">
            Your browser, unfortunately, is not supported by Resumable.js. The library requires support for <a href="http://www.w3.org/TR/FileAPI/">the HTML5 File API</a> along with <a href="http://www.w3.org/TR/FileAPI/#normalization-of-params">file slicing</a>.
        </div>
        <div class="resumable-drop">
            Drop video files here to upload or <a class="resumable-browse"><u>select from your computer</u></a>
        </div>
        <div class="resumable-progress">
            <table>
                <tr>
                    <td style="width: 100%"><div class="progress-container"><div class="progress-bar"></div></div></td>
                    <td class="progress-text" nowrap="nowrap"></td>
                    <td class="progress-pause" nowrap="nowrap">
                        <a href="#" onclick="r.upload(); return(false);" class="progress-resume-link"><img src="/assets/global_assets/images/icons/resume.png" title="Resume upload" /></a>
                        <a href="#" onclick="r.pause(); return(false);" class="progress-pause-link"><img src="/assets/global_assets/images/icons/pause.png" title="Pause upload" /></a>
                        <a href="#" onclick="r.cancel(); return(false);" class="progress-cancel-link"><img src="/assets/global_assets/images/icons/cancel.png" title="Cancel upload" /></a>
                    </td>
                </tr>
            </table>
        </div>
        <ul class="nav nav-sidebar mb-2 resumable-list p-0 pl-3 m-0" data-nav-type="accordion"></ul>
    </div>

    <script>
        var r = new Resumable({
            target: '/panel/uploadRadioChannelFile',
            chunkSize: 1 * 1024 * 1024,
            testChunks: false,
            throttleProgressCallbacks: 1,
            headers:{
                'X-CSRF-Token' :"{{ csrf_token() }}"
            },
            query:{
                _token : "{{ csrf_token() }}"
            }
        });
        // Resumable.js isn't supported, fall back on a different method
        if (!r.support) {
            $('.resumable-error').show();
        } else {
            // Show a place for dropping/selecting files
            $('.resumable-drop').show();
            r.assignDrop($('.resumable-drop')[0]);
            r.assignBrowse($('.resumable-browse')[0]);
    
            // Handle file add event
            r.on('fileAdded', function (file) {
                // Show progress pabr
                $('.resumable-progress, .resumable-list').show();
                // Show pause, hide resume
                $('.resumable-progress .progress-resume-link').hide();
                $('.resumable-progress .progress-pause-link').show();
                // Add the file to the list
                $('.resumable-list').append('<li class="nav-item resumable-file-' + file.uniqueIdentifier + '">Uploading <span class="resumable-file-name"></span> <span class="resumable-file-progress"></span>');
                $('.resumable-file-' + file.uniqueIdentifier + ' .resumable-file-name').html(file.fileName);
                // Actually start the upload
                r.upload();
            });
            r.on('pause', function () {
                // Show resume, hide pause
                $('.resumable-progress .progress-resume-link').show();
                $('.resumable-progress .progress-pause-link').hide();
            });
            r.on('complete', function () {
                // Hide pause/resume when the upload has completed
                $('.resumable-progress .progress-resume-link, .resumable-progress .progress-pause-link').hide();
            });
            r.on('fileSuccess', function (file, message) {
                // Reflect that the file upload has completed
                $('.resumable-file-' + file.uniqueIdentifier + ' .resumable-file-progress').html('(completed)');
            });
            r.on('fileError', function (file, message) {
                // Reflect that the file upload has resulted in error
                $('.resumable-file-' + file.uniqueIdentifier + ' .resumable-file-progress').html('(file could not be uploaded: ' + message + ')');
            });
            r.on('fileProgress', function (file) {
                // Handle progress for both the file and the overall upload
                $('.resumable-file-' + file.uniqueIdentifier + ' .resumable-file-progress').html(Math.floor(file.progress() * 100) + '%');
                $('.progress-bar').css({width: Math.floor(r.progress() * 100) + '%'});
            });
            r.on('cancel', function () {
                $('.resumable-file-progress').html('canceled');
            });
            r.on('uploadStart', function () {
                // Show pause, hide resume
                $('.resumable-progress .progress-resume-link').hide();
                $('.resumable-progress .progress-pause-link').show();
            });
        }
    </script>

**route**:

    Route::post('uploadRadioChannelFile', 'UploadController@upload');

and **`controller`**:

    class UploadController extends Controller
    {
        public function upload(Request $request)
        {
            try {
                $receiver = new FileReceiver("file", $request, HandlerFactory::classFromRequest($request));
    
                if ($receiver->isUploaded() === false) {
                    return response()->json([
                        "done" => '',
                        'status' => false
                    ]);
                }
    
                $save = $receiver->receive();
    
                if ($save->isFinished()) {
                    return $this->saveFile($save->getFile());
                }
    
                $handler = $save->handler();
    
                return response()->json([
                    "done" => $handler->getPercentageDone(),
                    'status' => true
                ]);
            } catch (UploadFailedException $e) {
            }
        }
    
        protected function saveFile(UploadedFile $file)
        {
            $fileName = $this->createFilename($file);
            //$mime = str_replace('/', '-', $file->getMimeType());
            $dateFolder = Carbon::now()->year;
    
            $public_html = config('app.public_path');
    
            $filePath = "upload/{$dateFolder}/";
    
            $file->move($public_html.$filePath, $fileName);
    
            return response()->json([
                'path' => $filePath,
                'name' => $fileName,
                'ffff' => $file->getClientOriginalName(),
            ]);
        }
    
        protected function createFilename(UploadedFile $file)
        {
            //$extension = $file->getClientOriginalExtension();
            //$filename = str_replace("." . $extension, "", $file->getClientOriginalName()); // Filename without extension
            //$filename .= "_" . md5(time()) . "." . $extension;
    
            return time() . '.' . $file->getClientOriginalExtension();
        }
    }

**Comment by pionl** [comment]
Here is the fix - will be soon merged https://github.com/pionl/laravel-chunk-upload/pull/98

**Comment by pionl** [comment]
Fixed a bug and added a support for Laravel 7 in [v1.4.0]( https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.4.0)

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).

If you created a packagist entry please mark it as deprecated (in favor of this package) or delete it - it can confuse people. 

Thank you for your patience.
