### ISSUE TITLE
Laravel 8 compatibility?

### ISSUE THREAD

**Issue by beornlake** [pionl/laravel-chunk-upload#112]
Wondering where this package stands on compatibility with Laravel 8. Looks like @drjdr has a [fork](https://github.com/drjdr/laravel-chunk-upload) that makes some [cursory changes](https://github.com/drjdr/laravel-chunk-upload/compare) to the composer.json, but that’s about it. Doesn’t look like he’s submitted a merge request for that, though...

**Comment by MahdiPishguy** [comment]
@beornlake yes your right, how can we use this fork repository? is it possible?

**Comment by pionl** [comment]
🚀 Laravel 8 support - all acceptance tests passed
