### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by match** [pionl/laravel-chunk-upload#113]
Laravel 8 released in September 8. However this package does not support the latest version by dependencies reason, so it should be support.

**Comment by MahdiPishguy** [comment]
+1

**Comment by wimil** [comment]
same...

**Comment by darrencraig** [comment]
+1

**Comment by ricocrivelli** [comment]
There is a working fork at https://github.com/drjdr/laravel-chunk-upload

There a PR to merge this repo.

**Comment by AllCdnBoy** [comment]
thanks for the update rico.  Hopefully this will get merged soon.

**Comment by pionl** [comment]
🚀 Laravel 8 support - all acceptance tests passed
