### ISSUE TITLE
How to change where chunked files goes ?

### ISSUE THREAD

**Issue by ysrodrigues** [pionl/laravel-chunk-upload#118]
Hi there,

Thanks for this amazing package it's save me a lot of time. A wonderful integration with Dropzonejs.

But I need to change the folder where all chunked files goes, but i can't find where i change it.

Thx

**Comment by rbsl-yasmin** [comment]
You can change the path and disk from the config file of this package chunk-upload.php

**Comment by ysrodrigues** [comment]
Thx a lot, i didn't see this config file.
