### ISSUE TITLE
Add support for laravel 9

### ISSUE THREAD

**Issue by marcoax** [pionl/laravel-chunk-upload#127]
Please add support for laravel 9

**Comment by cmple** [comment]
@pionl any update on this?

**Comment by padre** [comment]
@pionl will this package be updated for Laravel 9 support?

Thanks!

**Comment by AbdelzaherMuhammed** [comment]
@pionl If not updated.. is there any substitution for the package ?

**Comment by syed-sohaaib** [comment]
@pionl when would this great package be expected to work with laravel 9?

**Comment by pionl** [comment]
Please use `v1.5.0` and check #129
