### ISSUE TITLE
Cloudflare and chunking 

### ISSUE THREAD

**Issue by Chinese1904** [pionl/laravel-chunk-upload#13]
Hi!

I am not too familiar with Cloudflare and it seems that their support does not respond to my inquiry either, so I figured I might as well ask here.

As an example I set the chunk size to 50mb here: http://testnow.ga/jquery-file-upload
The issue I have is that the TTFB (time to first byte) is very long after a chunk is completed and it has something to do with Cloudflare. A workaround would be to use the uploader on a subdomain, but I would rather not.

![Image of issue](http://i.imgur.com/PmaEuSP.png)

As you can see it takes 1.2 mins to upload the 50mb chunk, then 30 seconds to process it through the Cloudflare system. Is there a workaround that anyone knows that could maybe ignore reporting back to Cloudflare to prevent such long wait times?

Thanks :-)

**Comment by pionl** [comment]
I think there could be a problem with the writing the chunk. I would try to lower the chunk size into smaller sizes (try 5MB). 

Second try could be analyze parts of code which takes to long to process and then we can think about solution.

**Comment by Chinese1904** [comment]
I have done extensive analyzing and the issue was on Cloudflare's end trying process (?) those files. Even with 5MB chunks, it would take 3-5 seconds waiting - TTFB (peaking at 15 secs). Only way to solve this apparently is to use the uploader on a subdomain or get rid of Cloudflare. I chose the latter haha 

Thanks for you help!

**Comment by pionl** [comment]
Good to know :) Wish you a good luck in solving the issue later on.
