### ISSUE TITLE
How i can write feature tests in laravel

### ISSUE THREAD

**Issue by azamatgusov033** [pionl/laravel-chunk-upload#134]
I must write controller video load feature test, but i don' t know how i can do this

**Comment by pionl** [comment]
Hey, what is your aim of the test? You want to check the PHP code (feature) or test also JS code with the PHP code (acceptance test)?

For acceptance test you can check https://github.com/pionl/laravel-chunk-upload-example which contains tests in codeceptjs for supported Laravel versions.

For feature test - you should be able to send a request with a file (or mock the request). Should not be hard to do so.

**Comment by pionl** [comment]
I've not made any tests. But you can update readme if you want 👍
