### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by maciek-szn** [pionl/laravel-chunk-upload#147]
Looks like [Laravel 10 will be released in one week](https://laravel.com/docs/9.x/releases#support-policy). Are there any chances for update?

**Comment by pionl** [comment]
Hi, you can try add the support for it if you have the time.

I'll try to find some, but cant promise (I've already a lot of work planned for the weekend)

**Comment by maciek-szn** [comment]
> Hi, you can try add the support for it if you have the time.

I tried to do that (#149) but I'm not sure if that's enough

**Comment by pionl** [comment]
Thank you, it needs to be tested against Laravel 10, Im using this repo for it https://github.com/pionl/laravel-chunk-upload-example

**Comment by maciek-szn** [comment]
> Thank you, it needs to be tested against Laravel 10, Im using this repo for it https://github.com/pionl/laravel-chunk-upload-example

I'm sorry, I've tried to run the test according to your instructions, but apparently my knowledge is too low. We have to wait for someone else to do it.

**Comment by pionl** [comment]
@maciek-szn thank you for trying, I'll try to find time this week. M.

**Comment by Kurbzz** [comment]
Really appreciate this, from Paris :)

**Comment by pionl** [comment]
I've updated the to Laravel 10 + PHPUnit 10 and all works well.

All green. Version [v1.5.2 added](https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.5.2).

<img width="924" alt="Snímek obrazovky 2023-03-15 v 21 48 52" src="https://user-images.githubusercontent.com/1878831/225440672-6be2a51e-dc5e-435a-bfc4-fa506681b1c8.png">

For future if someone wants to help to check their changes check [this commit in laravel-chunk-example](https://github.com/pionl/laravel-chunk-upload-example/commit/78311cbcc9654d5f0b0be2ab583e9c176bfc9053).

Thanks for waiting for this. Have a great day all.

**Comment by RTippin** [comment]
Thank you so much @pionl

**Comment by elijahcruz12** [comment]
Thank you!

**Comment by pionl** [comment]
> Thank you so much @pionl 

@RTippin thank you!
