### ISSUE TITLE
PHP Client for upload

### ISSUE THREAD

**Issue by layarkaca21** [pionl/laravel-chunk-upload#155]
Hi all,
As i know, laravel-chunk-upload only in javascript front-end.
Any script i can use to upload file using PHP or curl to  a server laravel-chunk-upload ?

**Comment by pionl** [comment]
Not I know of, but you could pick some JS frontend and their request structure and send it via curl / HTTP client with same way. 

Check the PHP for the implementation and extract what you need to set.

**Comment by layarkaca21** [comment]
okay thanks bro
