### ISSUE TITLE
Wrong detection of upload finish on 32bit PHP

### ISSUE THREAD

**Issue by Nerg4l** [pionl/laravel-chunk-upload#16]
Hi!

On 32bit PHP the maximum of an integer is 2147483647.
In ContentRangeUploadHandler class on lines 93,94,95 intval() is used so bytesStart, bytesEnd and bytesTotal max value is 2147483647. So after about 2GB the script thinks that the upload is finished.

**Comment by pionl** [comment]
Hi @Nerg4l , nice catch! I didn't realize this use case. After reading, the float value should handle bigger size. Do you agree? I can push the change today.

**Comment by Nerg4l** [comment]
Just tested the code with floatval() and it works for me as expected. The problem with float is that it is platform-dependant and floatval() returns INF (infinite) constant when it gets a number which is bigger than the maximum.
So the script should throw an exception if floatval() returns INF.

**Comment by pionl** [comment]
@Nerg4l thank you for tests and direction, I've implemented the changes + added tests and works as expected. Updated to `1.0.4` version.

**Comment by ashbeats** [comment]
Sorry to be a downer... but there may be more tests needed to handle different php platforms. Specifically with floating point precision with "/" and "*" operators. If you're shifting to floats, i recommend switching to BCMath for the division/multiplication operations and upping the precision ini value in php.

**Comment by pionl** [comment]
Hi @ashbeats, not sure if follow correctly, but the uploader will send only int value. Float value should not be sent. We are using float only to overcome the 32 bit restriction. The values are float but without decimal points. Also `getPercentageDone` will always `ceil` the value. 

I've added also `OS X` to travis to check the test calculations with int values.

I think it's not necessary to add `BCMath` as required dependency.

Best regards
