### ISSUE TITLE
pion / chunk-upload.php

### ISSUE THREAD

**Issue by mina-8** [pionl/laravel-chunk-upload#160]
return [
    /*
     * The storage config
     */
    'storage' => [
        /*
         * Returns the folder name of the chunks. The location is in storage/app/{folder_name}
         */
        'chunks' => 'chunks',
        'disk' => 's3',
    ]

how to change disk from local to s3 to upload chunk file to my bucket s3 ?

**Comment by pionl** [comment]
You can use s3 chunk cloud upload using their SDK - currently not in this package or you can upload it after chunks were merged: https://github.com/pionl/laravel-chunk-upload/wiki/Saving-to-Cloud
