### ISSUE TITLE
Upload error not handled

### ISSUE THREAD

**Issue by Nerg4l** [pionl/laravel-chunk-upload#17]
Hi!

This almost made me insane. It took me two hours of debugging on a test server.
When an upload error occurs the code gives "Failed to open input stream" error message, because the first time this cause a problem in the code is at ChunkSave:191, because the path name of the uploaded file is empty.
I think the constructor of FileReceiver should handle upload errors but this more of a feature request than a bug.

**Comment by pionl** [comment]
HI @Nerg4l,

could you share me your code how you init the FileReceiver? Thank you

**Comment by Nerg4l** [comment]
I use the most basic initialization.

	$fileReceiver = new FileReceiver('file', $request, HandlerFactory::classFromRequest($request));

My problem was that the `post_max_size` in `php.ini` was set to 2M and the chunk size was 5MB so the upload failed with error code 1 which is `UPLOAD_ERR_INI_SIZE`. However the **Failed to open input stream** error message mislead me.

**Comment by pionl** [comment]
Thank you. I'm sorry for this error, I thought that larvel will raise exception on error.

I've updated code to raise exception when there is an error. Is it ok for you now?

Have a great day,

**Comment by Nerg4l** [comment]
Absolutely. Thank you for the great work.

**Comment by maulik0007** [comment]
i am getting this error on shared hosting with chunk upload using dropzone, its working fine in local but not working in live site.

Note: in local i can upload video of 90M but in live server i can upload video of 3M and when try to upload video of 90M it gives below error.

exception
: 
"Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException"
file
: 
"/home/project/vendor/symfony/http-foundation/File/File.php"
line
: 
36
message
: 
"The file \"/home/project/storage/app/chunks/./videoplayback.mp4-bBG5AJcXMpoAlJEt7GgaGkGAz1JEQcixbZ3FCoOn.part\" does not exist"
