### ISSUE TITLE
mkdir(): Permission denied

### ISSUE THREAD

**Issue by TheKillerremijn** [pionl/laravel-chunk-upload#2]
Hello,
We are having an issue with the uploader, When uploading a file it throws an error on `createChunksFolderIfNeeded() line 216` in Save\ChunkSave
$path appears the be the directory specified in `storage.chunks`, whist mkdir() needs an absolute path
`dump($path)` prints `'chunks/'`

Thank you,
Nick

**Comment by pionl** [comment]
@TheKillerremijn thank you for the info, made a mistake after small refactor in a hurry (thought it was already fixed). If there is any other problem, let me know. Works well for me.
