### ISSUE TITLE
Remove Laravel dependency

### ISSUE THREAD

**Issue by vedmant** [pionl/laravel-chunk-upload#21]
Hi, I'm using multiple Illuminate packages instead of Laravel and after installing this package it installed whole laravel framework that I don't need, could you remove direct laravel dependency and instead make it depend on some particular Illuminate packages it requires. It would be great to allow it to work standalone in general.

**Comment by pionl** [comment]
Seems useful, will do

**Comment by pionl** [comment]
Depedency list changed, please check the latest version `1.1.3`.
