### ISSUE TITLE
Is dropzone.js working with this ?

### ISSUE THREAD

**Issue by leonekmi** [pionl/laravel-chunk-upload#22]
I cannot make this package work with dropzone.js, it's the chunking method different or i have an error in my code (i copied from example) ?

For giving details, the chunk is always recognised as a full file.

**Comment by s1rc** [comment]
Seconded. 

Running into the same issue. Would prefer not to have to switch out our JS uploader.

**Comment by pionl** [comment]
HI @leonekmi, at this moment there is no implementation for dropzone.js, if someone has a time, it can be implemented without problem (it just needs to handle the dropzone.js format)

**Comment by pionl** [comment]
Implementation added for chunked upload from DropZone, use `1.1.3` version 👍
