### ISSUE TITLE
Google Cloud Storage Support

### ISSUE THREAD

**Issue by gtaure** [pionl/laravel-chunk-upload#24]
I am using **"superbalist/laravel-google-cloud-storage"** to add Google Cloud Storage disk to Lravel's Storage facade. Calling `Storage::disk('gcs')->put('filename.ext, $data);` saves the file to Google Cloud Storage.

I hope that you can add Google Cloud Storage support to **"pionl/laravel-chunk-upload"** with the help of **"superbalist/laravel-google-cloud-storage"**.

**Comment by pionl** [comment]
Hi,
you are able to use Cloud storage when chunk is completed. 
For my point of view it's not sufficient to send chunks to cloud storage and then delete them.

When you are saving a file, just load the data from received UploadFile, upload to GCS and then delete the file. Be aware of a large files.

**Comment by gtaure** [comment]
Hi,

Sorry, I forgot to mention that I am using Google App Engine's Flexible Environment. This does not allow writing to disk that is why chunk upload is not working. It could not save the chunked parts of the file to the system disk before moving it to Google Cloud Storage.

**Comment by pionl** [comment]
Now I get it, at this moment it's very hard to implement - all files must be sent to server, then downloaded for merging and then re-uploaded - this will take forever for huge files.

There must be some kind of tmp folder on Google App Engine's Flexible Environment where to store chunks. Is it possible to save files for some time?

**Comment by gtaure** [comment]
Well, they said we can write ephemeral files but right now I am having difficulty performing it as their server is responding a permission issue.

I am thinking maybe we could use **"superbalist/laravel-google-cloud-storage"** along with **"pionl/laravel-chunk-upload"** to achieve saving chunk files directly to GCS.

With **"superbalist/laravel-google-cloud-storage"**, I was able to save files directly to GCS but chunked files saves it differently.

**Comment by pionl** [comment]
Unfortunately bas I already sent, It would be unusable at this moment. Every chunk would be to cloud and then downloaded again for merging. Also, for merging we need to use file in local instance to be able to merge the data - otherwise we would need to use memory which is nonsense if you understand.

I Would focus on resolving the tmp folder (change the path of the cache folder, like using `sys_get_temp_dir`). I think this should work: 
1. Setup a new disk with `sys_get_temp_dir`
2. Use it as a cache folder for uploader

**Comment by DUDU54** [comment]
Hi, i faced this problem cause i use, for a project, Google App Engine as the doc said the request of same user can be dispatch to one of the instance randomly ,some part could be on the wrong instance and the upload could fail.

> App Engine runs multiple instances of your application, and each instance has its own web server for handling requests. Any request can be routed to any instance, so consecutive requests from the same user are not necessarily sent to the same instance.
 https://cloud.google.com/appengine/docs/standard/php7/how-requests-are-handled

So i have done some modification to the package to upload each part to Google Cloud Storage and then when they are all uploaded, we get each part from Google Cloud Storage and build the final chunk on the current instance.
you can check it here => https://github.com/DUDU54/laravel-chunk-upload/commit/3c29dbf262beecada9a522a53fdceb090e6e7082
