### ISSUE TITLE
Strange issue with `$save->getFile()`

### ISSUE THREAD

**Issue by rubybrowncoat** [pionl/laravel-chunk-upload#26]
I'm having an issue with chunked uploads at `$save->getFile()`, from the example method below, that returns the last uploaded chunk even after passing the `$save->isFinished()` check.

The uploadFile method is mostly identical to the provided example:
```php
    public function uploadFile(FileReceiver $receiver, Request $request) {
        if ($receiver->isUploaded()) {
            $save = $receiver->receive();
            if ($save->isFinished()) {
                return $this->saveFile($save->getFile(), $request);
            } else {
                /** @var AbstractHandler $handler */
                $handler = $save->handler();
                
                return response()->json([
                    "done" => $handler->getPercentageDone(),
                ]);
            }
        } else {
            throw new UploadMissingFileException();
        }
    }
```

Am I doing something wrong?

For example when I upload a file that is about 8MB with a set chunk size is of 1MB, chunks are all uploaded correctly, `.part` files are created but this is what `$save->getFile()` is returning (it's only the last chunk, with a size of about 890KB):
```php
UploadedFile {#313
  -test: true
  -originalName: "blob"
  -mimeType: "application/octet-stream"
  -size: 894516
  -error: 0
  #hashName: null
  path: "/Users/user/Sites/project/storage/app/chunks"
  filename: "blob-MQzSnbPSF2TpIxPeAYY5WzhgqdcAXTY5KzkVJfEE-8.part"
  basename: "blob-MQzSnbPSF2TpIxPeAYY5WzhgqdcAXTY5KzkVJfEE-8.part"
  pathname: "/Users/user/Sites/project/storage/app/chunks/blob-MQzSnbPSF2TpIxPeAYY5WzhgqdcAXTY5KzkVJfEE-8.part"
  extension: "part"
  realPath: "/Users/user/Sites/project/storage/app/chunks/blob-MQzSnbPSF2TpIxPeAYY5WzhgqdcAXTY5KzkVJfEE-8.part"
  aTime: 2018-01-19 11:21:19
  mTime: 2018-01-19 11:21:19
  cTime: 2018-01-19 11:21:19
  inode: 8597363617
  size: 894516
  perms: 0100644
  owner: 501
  group: 20
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
}
```

I store what `$save->getFile()` returns, and that means that any chunked file is corrupted because it's composed of only its last chunk's bytes.

I'm using the plupload `ChunksInRequestUploadHandler` handler.
I'm on Laravel 5.5.31.

**Comment by pionl** [comment]
Hi, 
the problem is probably with the setup you are using. There should be only single part file. All chunks are appended on upload. I would guess that on each chunk upload name of the file is different. What JS library you are using?

The JS library should send all the cookies, if you don't want to send cookies you can change the chunk naming to use `IP address` instead: https://github.com/pionl/laravel-chunk-upload#cross-domain-request, if this won't help, there then please include `$request->file('file')` and current headers for at least 2 chunks. 

Thank you,
Martin

**Comment by rubybrowncoat** [comment]
I am using PLUpload to manage the uploads.
I tested one 5.4MB file with 1MB chunks, and here are the logs you asked:

Cookies sent on each request (seems correct, identical for all requests):
```
cookie:
  gsScrollPos-1085=0;
  gsScrollPos-723=;
  XSRF-TOKEN=eyJpdiI6IitBS05rY0ZUdmdEbUhBK1RnNTZ0VGc9PSIsInZhbHVlIjoieDJtNU1HSTV5OE4xclQ4V0FId2krWUhSNm92WWZ4c1dBZVwvdG40ZUJBdG16b1ExWjBTVmR5eTNKMkFtam9MbEZCWE9SdHhxWjl2UFcxdzlzRDNIcGpnPT0iLCJtYWMiOiJhYzY3Y2NlMDc3ZWFjNWE3MGM1MWIzZjQ3ZTk1Y2UyODMwYTI4ZWYyZjE5ZjA3ZjdkMTJiYmNhOWY0YzI4YmZjIn0%3D;
  laravel_session=eyJpdiI6IjlHcE1vQmc2djhHamlnTWx1eHZDNVE9PSIsInZhbHVlIjoibWJoalwvRm1XVGJzSVgreWtrdU9lRWFIV000RHZDdzgzRXJYUVlPZW9CQ1BwWHBrV2hteEpacTBhUXZ5RVo5R2NVTjgxUnNBRWFoa0tYZkJCXC9PTlFGUT09IiwibWFjIjoiNjExMjk3OGU3Njc0ODk2Yjg2ZDUxMmI5YjZmZTcxZTI2NzUxZmU0Y2UwZDNiNDkzZDcwNWNhMmU3MWJlZDcxYyJ9;
  io=xaNUvPem3pBywiiyAAAi
```

The request payload (identical but for the "chunk" property which increments on each request):
```
------WebKitFormBoundaryM7NB7dKAJJ4Y9EsD
Content-Disposition: form-data; name="name"

images_for_tests.zip
------WebKitFormBoundaryM7NB7dKAJJ4Y9EsD
Content-Disposition: form-data; name="chunk"

0
------WebKitFormBoundaryM7NB7dKAJJ4Y9EsD
Content-Disposition: form-data; name="chunks"

6
------WebKitFormBoundaryM7NB7dKAJJ4Y9EsD
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: application/octet-stream


------WebKitFormBoundaryM7NB7dKAJJ4Y9EsD--
```

The log for `$request->file('file')` on at least 2 chunk (I've included all 6):
```
local.INFO: /private/var/tmp/phpwh4y4Q  
local.INFO: /private/var/tmp/phpIdCI0H  
local.INFO: /private/var/tmp/phpMD8qoO  
local.INFO: /private/var/tmp/phpgcQIFU  
local.INFO: /private/var/tmp/phpeapzYs  
local.INFO: /private/var/tmp/phpRsxayg  
```

**Comment by pionl** [comment]
Very interesting. And the names of the part files? Can you copy your config file? `chunk-upload`. I've tried the example and works as expected :/

**Comment by rubybrowncoat** [comment]
My `chunk-upload.php` config (I think it's the default):
```
<?php
return [

    /**
     * The storage config
     */
    "storage" => [
        /**
         * Returns the folder name of the chunks. The location is in storage/app/{folder_name}
         */
        "chunks" => "chunks",
        "disk" => "local"
    ],
    "clear" => [
        /**
         * How old chunks we should delete
         */
        "timestamp" => "-3 HOURS",
        "schedule" => [
            "enabled" => true,
            "cron" => "0 */1 * * * *" // run every hour
        ]
    ],
    "chunk" => [
        // setup for the chunk naming setup to ensure same name upload at same time
        "name" => [
            "use" => [
                "session" => true, // should the chunk name use the session id? The uploader must send cookie!,
                "browser" => false // instead of session we can use the ip and browser?
            ]
        ]
    ]
];
```

Part filenames are not really useful per-se (they are all pretty much like this):
```
blob-zqQyJBHJyQSbkOe9zm5bdO1xLM44SsC0h3LdZ4Jz-9.part
blob-zoqpfjARYBG46J21hU1hnKRDsfo0Z1Ahp85LENEP-9.part
blob-zLYSNRvZKCtV39kHabAdkqSk9bKIaSwlMoSY6C1h-17.part
blob-zjh4I6tWkYNuYNCNJBg06aEIcNZ1FsO2gPv1T7NF-6.part
```

I'm on version 5.5.31 of the laravel/framework, maybe it's something weird on that version? Seems unlikely.

**Comment by pionl** [comment]
Config is default, should be OK.

I agree that there is a problem with the naming. But it's constructed only with the file name (which is same for you use case), the session id and number of chunks. We can see, that the session is different - it's reconstructed on every request. I would recommend to use browser = true and session = false.

Probably the app is not receiving the cookie or your session is set to be regenerated.

**Comment by 2n2n** [comment]
Hi @pionl I also get the same issue with DropzoneJS. actually, based from your sample the file is segregated based on their file type, if I tried to upload a .mp4 file it's stored in the /storage/video-mp4/file.mp4, and also it tries to store some non-working .mp4 files (i think it's the chunks) in the /storage/application-octet-stream folder.

PS.
I also get the wrong filename after the upload.

**Comment by 2n2n** [comment]
@pionl finally it worked, you were right, after setting the browser = true and session = false. thank you very much.

**Comment by rubybrowncoat** [comment]
While browser = true and session = false correctly solved the issue, it wasn't what I was looking for.

I have solved my problem, and it was due to an oversight by me and something I think the documentation could mention (it's not the documentation's fault, obviously, since it specifically says multiple times that the package is using session) to preempt this mistake from happening to anyone else as distracted as I am.

My upload endpoints were created under the api.php route provider because we implement jwt authentication and other mechanisms. The problems is that the api group doesn't implement the StartSession middleware (it also throttles requests so that big file chunking is problematic when the amount of chunks exceeds the throttle setting in the throttle time, which can happen often).

I didn't want to change the api group for all other apis in the application, so, in the end, I created a new route provider and a new route group so that I could load the middlewares this package expects and the authentication middleware I needed.

**Comment by pionl** [comment]
@rubybrowncoat @2n2n New version will automatically detect if session can be used (default config is session = true) - if session is not initialized (`api` route will not initialize the session) it will use browser data instead. Thanks for all the feedback - this feature should make it way easier to setup.
