### ISSUE TITLE
[Vote] Add simultaneousUploads support

### ISSUE THREAD

**Issue by pionl** [pionl/laravel-chunk-upload#27]
Currently we do not support `simultaneousUploads`, but we can add it. It needs to move merging of files at last chunk. This feature will be slower than appending on upload but is doable.

Please vote if it necessary to add this feature.

Thank you.

**Comment by MrGekko** [comment]
Are you still waiting for more feedback to consider this?

**Comment by pionl** [comment]
At this moment yes - my time is limited (I would like to rewrite the `how to use it`, it's to complicated).

Ofcouse, if someone would like to try his skills and make this feature can go ahead (consulting is not a problem).

**Comment by richard457** [comment]
That can be useful in most cases when you need to handle many request at time.

**Comment by pionl** [comment]
@richard457 It support multiple file uploads in separate requests, not in single request ;)
