### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by thehelvetian** [pionl/laravel-chunk-upload#29]
Adjust `composer.json` to include Laravel 5.6

**Comment by pionl** [comment]
Hi @thehelvetian, I've updated the composer.json. Could you confirm that (dev version - master branch) that it is working? Currently I do not have PHP 7.1 prepared. This way it would be quicker. Thank you

**Comment by thehelvetian** [comment]
Hi @pionl, that's a confirm. It's working perfectly. You're good to tag & release. Thanks!
