### ISSUE TITLE
Can't get the file complete

### ISSUE THREAD

**Issue by alejogutierrez** [pionl/laravel-chunk-upload#3]
I don't know if I'm using the library wrong but always got the file incomplete.
I'm using laravel 5.3 with homestead, and plupload for the frontend.

In the example you have the following lines:
// save the file and return any response you need
return $this->saveFile($save->getFile());

I suppose that we have to implement the saveFile method, so when I try to move the file
to the new location it looks like a chunk.
When I look at the storage_path sometimes appears just one part of the blob, most of the time the last part.

Can you provide a more explicit example or is there something I'm missing?
Thanks by the way, nice work.

**Comment by pionl** [comment]
Hi @alejogutierrez , thanks for the feedback on the docs. Will write some update. When using `$save->getFile()` you will get the `UploadedFile` instance and you can use it's own functions.

```php
use Illuminate\Http\UploadedFile;

public funciton saveFile(UploadedFile $file) {
            $fileName = $file->getFilename();
            $filePath = "upload/".date("Y-m-d")."/";
            $finalPath = storage_path("app/".$filePath);
// move the file name
            $file->move($finalPath, $fileName);
}
```

**Comment by pionl** [comment]
Hi @alejogutierrez, I would recommend to use the latest version. Closing issue - no reaction. Feel free to contact me if problem persists.
