### ISSUE TITLE
Integration with: vue-upload-component

### ISSUE THREAD

**Issue by thunder87** [pionl/laravel-chunk-upload#31]
An integration (Handler) with the vue-upload-component would be a very nice addition :)
[Vue Upload Component](https://github.com/lian-yue/vue-upload-component)

**Comment by hatembelkhiria** [comment]
when i used that component, chunks not merged and it doesn't save all chunks. do u have any solution?

**Comment by thunder87** [comment]
@hatembelkhiria I modified the vue-dropzone component with custom styling as it supports chunking as an alternative.

**Comment by pionl** [comment]
Hi guys, is there any online example that I can check? We should be able to check what the component sends.

**Comment by Feniksss** [comment]
any news about this loader?

**Comment by pionl** [comment]
At this moment no contributor has been found
