### ISSUE TITLE
All chunked upload are being cancelled on the server (Xampp working fine)

### ISSUE THREAD

**Issue by tomnyc** [pionl/laravel-chunk-upload#33]
I am using Vue and Vue Dropzone for the Frontend.
Everything is working fine on my local Xampp.
For smaller files than my configured chunk size I am using a non-chunked upload with Laravel file upload methods.
Only files bigger than the chunk size are processed by laravel-chunk-upload.

In my productive environment on my managed server chunked uploads are always cancelled and a 500 error is thrown.
It looks like no chunks are being created on the server at all.
My Laravel logfile states this error:

[2018-05-11 07:56:39] production.ERROR: The file "testfile.zip" was only partially uploaded. {"userId":1,"email":"test@domain.de","exception":"[object] (Pion\\Laravel\\ChunkUpload\\Exceptions\\UploadFailedException(code: 500): The file \"testfile.zip\" was only partially uploaded. at /html/myproject/vendor/pion/laravel-chunk-upload/src/Receiver/FileReceiver.php:66) 

Any ideas?

**Comment by pionl** [comment]
HI, unfortunatelly I have no experience with this error:

What server configuration you are using?

Try this: https://wordpress.stackexchange.com/questions/176465/failed-media-upload-the-uploaded-file-was-only-partially-uploaded

I't is definitely error within apache2 configuration.

**Comment by tomnyc** [comment]
I am using neither a root server nor a shared hosting.
We do have a Managed Server exclusively for us.
So I can change the php.ini a little bit but not the Apache configuration.

It looks like the installed Linux distribution is a gentoo.

I have checked your link but since I cannot change any Apache configuration settings I cannot experiment with libapache2-mod-php5filter / libapache2-mod-php5 or the KeepAlive flag.

Do you think I am stuck here and have to switch to a root server?

**Comment by pionl** [comment]
First I Would try to simple html5 upload - use standard multipart form with input[type=file] without any JS library and upload it (you can still use the chunk uploader). If it is successfully, I would try different library for test.

**Comment by hugeps** [comment]
Was this resolved?
