### ISSUE TITLE
Lumen support?

### ISSUE THREAD

**Issue by rmclellanduhin** [pionl/laravel-chunk-upload#42]
Anyone had any luck getting this package to work with Lumen?

**Comment by dodo438** [comment]
I am also looking for this...

**Comment by rmclellanduhin** [comment]
If you look at the fork I created of the project you should be able to get it working in Lumen. It took a little doing but we're using it now.

**Comment by pionl** [comment]
@rmclellanduhin Link to the fork? Thanks

**Comment by giancarlobianchi12** [comment]
@rmclellanduhin do you have the link of fork ? Thanks
@pionl lumen support ?

**Comment by svonian** [comment]
@giancarlobianchi12 I just ran into the same issue but got it working with a few tweaks see below:

1) Extend the \Pion\Laravel\ChunkUpload\Providers\ChunkUploadServiceProvider
```
class ChunkUploadServiceProvider extends \Pion\Laravel\ChunkUpload\Providers\ChunkUploadServiceProvider
{
    public function boot()
    {
        $config = $this->app->make(AbstractConfig::class);

        // I didn't need the scheduler or other features they provide so I was able to go with this

        $this->registerHandlers($config->handlers());
    }

    protected function registerConfig()
    {
        // Config options
        $configIndex = FileConfig::FILE_NAME;
        $configFileName = FileConfig::FILE_NAME.'.php';
        $configPath = __DIR__.'/../../config/'.$configFileName;

        // Publish the config
        $this->publishes([
            $configPath => config_path($configFileName),
        ]);

        // Merge the default config to prevent any crash or unfilled configs
        $this->mergeConfigFrom(
            $configPath,
            $configIndex
        );

        return $this;
    }
}
```

2) In your bootstrap/app.php
```
$app->register(\App\Providers\ChunkUploadServiceProvider::class);
```

3) Extend the handler so that it doesn't use sessions (the even if you set session to false in the config the method session() is still called and lumen doesn't use sessions by default)

```
namespace App\Vendor\ChunkUpload\Handler;

use Pion\Laravel\ChunkUpload\Handler\ChunksInRequestUploadHandler;

class ResumableJSUploadHandler extends ChunksInRequestUploadHandler
{
    public static function canUseSession()
    {
        return false;
    }
}
``` 

4) Finally, import the config and override the handler:
```
...
    'handlers' => [
        // A list of handlers/providers that will be appended to existing list of handlers
        'custom' => [],
        // Overrides the list of handlers - use only what you really want
        'override' => [
            \App\Vendor\ChunkUpload\Handler\ResumableJSUploadHandler::class
        ],
    ],
...
```

**Comment by giancarlobianchi12** [comment]
@svonian That works !! Thank you so much :D

**Comment by daalvand** [comment]
for schedule can use following code
`
        $this->callAfterResolving(Schedule::class, function (Schedule $schedule) use ($scheduleConfig){
            $schedule->command('uploads:clear')->cron(Arr::get($scheduleConfig, 'cron', '* * * * *'));
        });
`

**Comment by pvictorf** [comment]
> @giancarlobianchi12 I just ran into the same issue but got it working with a few tweaks see below:
> 
> 1. Extend the \Pion\Laravel\ChunkUpload\Providers\ChunkUploadServiceProvider
> 
> ```
> class ChunkUploadServiceProvider extends \Pion\Laravel\ChunkUpload\Providers\ChunkUploadServiceProvider
> {
>     public function boot()
>     {
>         $config = $this->app->make(AbstractConfig::class);
> 
>         // I didn't need the scheduler or other features they provide so I was able to go with this, as the booted methods don't exist in lumen
> 
>         $this->registerHandlers($config->handlers());
>     }
> 
>     protected function registerConfig()
>     {
>         // Config options
>         $configIndex = FileConfig::FILE_NAME;
>         $configFileName = FileConfig::FILE_NAME.'.php';
>         $configPath = __DIR__.'/../../config/'.$configFileName;
> 
>         // Publish the config
>         $this->publishes([
>             $configPath => config_path($configFileName),
>         ]);
> 
>         // Merge the default config to prevent any crash or unfilled configs
>         $this->mergeConfigFrom(
>             $configPath,
>             $configIndex
>         );
> 
>         return $this;
>     }
> }
> ```
> 
> 1. In your bootstrap/app.php register YOUR newly extended provider
> 
> ```
> $app->register(\App\Providers\ChunkUploadServiceProvider::class);
> ```
> 
> 1. Extend the handler so that it doesn't use sessions (the even if you set session to false in the config the method session() is still called and lumen doesn't use sessions by default)
> 
> ```
> namespace App\Vendor\ChunkUpload\Handler;
> 
> class ResumableJSUploadHandler extends \Pion\Laravel\ChunkUpload\Handler\ResumableJSUploadHandler
> {
>     public static function canUseSession()
>     {
>         return false;
>     }
> }
> ```
> 
> 1. Finally, import the config and override the handler to use YOUR newly extended handler
> 
> ```
> ...
>     'handlers' => [
>         // A list of handlers/providers that will be appended to existing list of handlers
>         'custom' => [],
>         // Overrides the list of handlers - use only what you really want
>         'override' => [
>             \App\Vendor\ChunkUpload\Handler\ResumableJSUploadHandler::class
>         ],
>     ],
> ...
> ```

Thanks I needed created this files:
```php

// Ultils/Helpers.php

<?php

if ( ! function_exists('config_path'))
{
    /**
     * Get the configuration path.
     *
     * @param  string $path
     * @return string
     */
    function config_path($path = '')
    {
        return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
    }
}
```

```php
// Handlers/ResumableJSUploadHandler.php

<?php

namespace App\Utils;

class ResumableJSUploadHandler extends \Pion\Laravel\ChunkUpload\Handler\ResumableJSUploadHandler
{
    public static function canUseSession()
    {
        return false;
    }
}
```


```php
// config/chunk-upload.php

<?php

return [
  'handlers' => [
    // A list of handlers/providers that will be appended to existing list of handlers
    'custom' => [],
    // Overrides the list of handlers - use only what you really want
    'override' => [
        \App\Utils\ResumableJSUploadHandler::class
    ],
  ],
];

```

And change **upload_max_filesize** with .htacess

**Comment by pionl** [comment]
PR are welcomed to add offical support. Thanks
