### ISSUE TITLE
chunks not being assembled

### ISSUE THREAD

**Issue by hadikmsh** [pionl/laravel-chunk-upload#43]
Hi
thank you for your useful package.
I started using chunk-upload from past week and for the first time it worked great but after some customization on your sample code and use your advance sample it stopped working.

the problem is that file is completely uploaded but only last chunk was saved on the upload folder while the other chunk is stored on the chunk folder and have not been assembled.

after that I uploaded the exact sample project on the server but it did not work correctly and have the same problem.

I have been using laravel 5.5 as a restful server and my front end including dropzone.js is on another server that uses api to send requests to the server .
this is my front end js code:
        var myDropzone = new Dropzone("#my-awesome-dropzone", {
            // Setup chunking
            chunking: true,
            url: window.RequestUrl + "api/v1/upload",
            method: "POST",
            maxFilesize: 400000000,
            chunkSize: 1000000,
            // If true, the individual chunks of a file are being uploaded simultaneously.
            parallelChunkUploads: true
        });

and this is my html:
<form class="dropzone" id="my-awesome-dropzone"></form>

and these are server response that I got when uploading a 1.1 Mb file.

{"path":"upload\/application-octet-stream\/2018-07-27\/","name":"1_ff5ac9c86fe043298217e80c071d4828.jpg","mime_type":"application-octet-stream"}

{"done":50,"status":true}

please help me.
regard.

**Comment by pionl** [comment]
Hi,

Please disable `parallelChunkUploads` to eliminate any issue with merging chunks.

If works same, try to disable session and use browser for naming due "api" endpoint. It should detect by it self, but you see if it's the problem,

https://github.com/pionl/laravel-chunk-upload/wiki/config

Thank you

**Comment by hadikmsh** [comment]
thank you so much.
i changed config file and it now works great.

**Comment by pionl** [comment]
Ok, I'll check why the automatic detection has failed. Have a great day
