### ISSUE TITLE
Last chunk left in chunks directory after successful upload

### ISSUE THREAD

**Issue by mirago** [pionl/laravel-chunk-upload#45]
hi, thanks for this package. I was wondering if there is a reason why the last chunk is left in the chunks folder even after successful upload? Or am I missing something?

**Comment by mirago** [comment]
Ohh, I think I was using laravel's 'store' method on uploaded file, and that actually copies the file. I need to use 'move' method instead. :D

**Comment by pionl** [comment]
HI, I was on holiday :) Yep, that is the correct method. Is the documentation written badly? What made you think store is the way to go?

The docs how to save the file are in wiki: https://github.com/pionl/laravel-chunk-upload/wiki/controller
