### ISSUE TITLE
Support Multipart Upload API for S3

### ISSUE THREAD

**Issue by LaedaSt** [pionl/laravel-chunk-upload#46]
Hello! I have a problem with chunking: I use dropzone.js and Laravel to upload large files. I expect a large file to be uploaded to s3, but upload just a last of his parts! As I can see, script doesn't glue these parts together as I expected. That`s why, I had one file before uploading and N files in s3. But I need also one large file in s3. Is there any ways to do that? Thank you!

**Comment by Sweeeeep** [comment]
+1

**Comment by pionl** [comment]
Hi there, you need to upload to upload the file to s3 after all chunks are merged.

Check this section: https://github.com/pionl/laravel-chunk-upload/wiki/Saving-to-Cloud

Or do you have problem that chunks are not locally merged?

**Comment by pionl** [comment]
Instead of calling saveFile you will use the code for saving to s3. Here is example of a controller: https://github.com/pionl/laravel-chunk-upload/wiki/controller

**Comment by nerg4l** [comment]
I think they want to take advantage of the [Multipart Upload API](https://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html)

> Multipart upload allows you to upload a single object as a set of parts. [...] You can upload these object parts independently and in any order.

**Comment by pionl** [comment]
Oh I see, it would need to implement some kind of "QueueSave" that would save the part and in a job would re-send it to Amazon. Also it would skip the finalization of the file. 

Unfortunately I do not use Amazon services. If any one wants this feature you are free to implement it (contact me on email if you need guidance).

**Comment by kmarkovic1** [comment]
Does the package have support for multipart upload now?

**Comment by kmarkovic1** [comment]
Hi :) Does the package have a support for multipart upload now?
