### ISSUE TITLE
Cross upload on different tab (chunk merging issue)

### ISSUE THREAD

**Issue by napster2k3** [pionl/laravel-chunk-upload#47]
Hi,

when I try to upload audios from two different tabs at the same time, audios get damaged.
I'm using a custom front end library with a custom handler.
Final chunk is the last to be uploaded as followed on your documentation

Any ideas?

Thanks in advance

**Comment by pionl** [comment]
Hi,

do they have same name? What library you are using? The drop zone (and etc) sends unique id that helps to prevent these issues.

**Comment by napster2k3** [comment]
It was on my end, fixed it.

Thanks for the reply
