### ISSUE TITLE
Proposal: Register upload handlers in config

### ISSUE THREAD

**Issue by nerg4l** [pionl/laravel-chunk-upload#50]
It would be great if the handler registration would be in the config file intead in the `HandlerFactory`. So handlers could work similarly to providers. This would make the library more extendable.

- Ability to remove unused handlers
- Developers could extend the library easyer (without the need of implementing the whole library)

What do you think about this?

**Comment by pionl** [comment]
Hi,

you already do not need to implement the whole library, you can call  `Handler:: register(MyOwnImplementation::class)`, the docs are in [Wiki](https://github.com/pionl/laravel-chunk-upload/wiki/More)

Anyway, you have a point. It would be easier to provider entry in config. I would not recommend to have in-built handlers in config (updating would be harder), but we could allow user to override the handlers. This should be pretty easy.

```php
... config
'handlers' => [
// A list of handlers/providers that will be appended to existing list of handlers
'custom' => []
// Overrides the list of handlers - use only what you really want
'override' => []
]
```

**Comment by pionl** [comment]
Working on it

**Comment by pionl** [comment]
I've updated the wiki:

- https://github.com/pionl/laravel-chunk-upload/wiki/Controller
- https://github.com/pionl/laravel-chunk-upload/wiki/custom-handler

Integration is updated to use config. Service provider is now partly unit tested (to cover this change).
