### ISSUE TITLE
Chunks merged in wrong order

### ISSUE THREAD

**Issue by ggolda** [pionl/laravel-chunk-upload#54]
Hi, I've faced a weird issue with this package using dropzone.js.
Lib version: `"pion/laravel-chunk-upload": "^1.2"`

Here are my dropzone configs:
```js
{
...
       maxFilesize: 300, // Mb
       timeout: 60000 * 3,
       chunking: true,
       acceptedFiles: '.zip',
       chunkSize: 10000000,
       autoProcessQueue: false,
       maxFiles: 1,
}
```
And settings from `chunk-upload.php`:
```php
'chunk' => [
        // setup for the chunk naming setup to ensure same name upload at same time
        'name' => [
            'use' => [
                'session' => false, // should the chunk name use the session id? The uploader must send cookie!,
                'browser' => true, // instead of session we can use the ip and browser?
            ],
        ],
    ],
```

When uploading a large file (around 230 Mb) `sometimes` I've faced an issue that chunks are merged in incorrect order and half of chunks are ignored.

Here are the `ls` result from `storage/app/chunks` folder with this bug reproduced: https://imgur.com/a/rfF3osg

As you can see, on the first screenshot we have 24 chunks, each has a size on 10 Mb. On the second screenshot you can see that chunks get merged incorrectly in random order (part 1 and then 20 - 
This bug reproduces not always, in 50% of cases and I don't know why.

Any help or advice? I've tried several `chunk` sizes from 2 Mb to 10 Mb, the larger the chunk size the less this bug reproduces (based on my observations).

**Comment by ggolda** [comment]
I was able to fix this issue by switching back to `session` and moving my controller from `api` middleware to `web` (session based).
As you can see from my screenshots above, for some reason chucks from a single user have different ids while using a `browser` setting.

**Comment by ggolda** [comment]
May be you can provide a way to override a default `file-naming` algorithm with a custom one? E.g. I can use `user-id` or other identifiers to construct chunks

**Comment by pionl** [comment]
HI @ggolda 

Fixed a bug and added a support for Laravel 7 in [v1.4.0]( https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.4.0)

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).

If you created a packagist entry please mark it as deprecated (in favor of this package) or delete it - it can confuse people. 

Thank you for your patience.
