### ISSUE TITLE
Some of the chunks are skipped when merging

### ISSUE THREAD

**Issue by bgmastermind** [pionl/laravel-chunk-upload#57]
While looking where the issue is coming from I got it fixed by
adding  sleep(3); right after 
protected function buildFullFileFromChunks()
and before
$chunkFiles = $this->getSavedChunksFiles()->all(); 

in ParallelSave.php

Issue is easy observed when uploading larger files. If chunks are with size 2MB, then more chunks are left over. If chunk size is 20mb then only 1-2 files are left over. For a 1.3 GB file. it is the same with dropzone and resumable. And it occurs when parallel uploading chunks. If i switch it to false, then upload is ok.

So my theory is that when last chunk gets uploaded the full file reconstruction starts. But I don't see a check if all chunks are uploaded, then start the reconstruction.

**Comment by pionl** [comment]
Hi. mainly there was a problem with incorrect chunk detection. Please try with new version.

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).

If you created a packagist entry please mark it as deprecated (in favor of this package) or delete it - it can confuse people. 

Thank you for your patience.
