### ISSUE TITLE
How to work with the response from the file upload?

### ISSUE THREAD

**Issue by eikem** [pionl/laravel-chunk-upload#59]
I use dropzone.js and Laravel 5.7. 

My script offers the option to add multiple Images and they get uploaded together with some extra Infos for each Image as well as an album Name and Year. It worked fine locally but on the Shared Hosting I had issues so I decided I need to look into chunking.

First issue was than that the Album Info got entered into the db for each chunk so I thought I should first upload the Images to the server, when they are all uploaded start another AJAX call to enter the data for the Album and the Images into the database, resize the images and move them into another folder.

The problem I now realised is when I upload 1 File of 2.5 Mb than I get 3 POST Request and the below 3 answers. As you can see, I would only want the first one. Why are there 2 files in application-octet-stream? Are they are the chunks? I don't have a chunks folder anymore, no idea why this is not created anymore. The problem is that I get the Name from the last Post response, but which is the name of a Chunk and not a file. I just don't know how to handle it to be able to send multiple files + each file got it's own form data + other Form Data like album name and description and the files have to stay in the order they are in the dropzone Queue since I use that as the sort Order. 
I have posted part of my dropzone code below where I try to work with the response from the File Upload. 

```
{"path":"upload\/image-jpeg\/2019-01-04\/","name":"20180714_121742_7c8bceedd34b1f605110936faec59d9e.jpg",
"mime_type":"image-jpeg"}

{"path":"upload\/application-octet-stream\/2019-01-04\/","name":"20180714_121742_7c8bceedd34b1f605110936faec59d9e.jpg","mime_type":"application-octet-stream"}

{"path":"upload\/application-octet-stream\/2019-01-04\/","name":"20180714_121742_31ae18f8f1d94a8ce3e89ed0b97496c8.jpg","mime_type":"application-octet-stream"}

Dropzone.options.myAwesomeDropzone = { // The camelized version of the ID of the form element
    autoProcessQueue: false,
    totalMaxsize: 100,
    parallelUploads: 1,  // since we're using a global 'currentFile', we could have issues if parallelUploads > 1, so we'll make it = 1
    maxFilesize: 10,   // max individual file size 1024 MB
    chunking: true,      // enable chunking
    forceChunking: true, // forces chunking when file.size < chunkSize
    parallelChunkUploads: false, // allows chunks to be uploaded in parallel (this is independent of the parallelUploads option)
    chunkSize: 1000000,  // chunk size 1,000,000 bytes (~1MB)
    retryChunks: true,   // retry chunks on failure
    retryChunksLimit: 10, // retry maximum of 3 times (default is 3)
    maxFiles:30,
    timeout: 600000,
    thumbnailWidth: 288,
    thumbnailHeight:192,
    thumbnailMethod: 'contain',  
    paramName:'file',
    acceptedFiles: ".jpg,.jpeg,.png",
    previewTemplate: previewTemplate,
    previewsContainer: "#previews", // Define the container to display the previews
    clickable: ".fileinput-button", // Define the element that should be used as click trigger to select files.
    countImages:0,
  
  
    params: function (files, xhr, chunk) {
         
        if (chunk) {
                return {
                    dzUuid: chunk.file.upload.uuid,
                    dzChunkIndex: chunk.index,
                    dzTotalFileSize: chunk.file.size,
                    dzCurrentChunkSize: chunk.dataBlock.data.size,
                    dzTotalChunkCount: chunk.file.upload.totalChunkCount,
                    dzChunkByteOffset: chunk.index * this.options.chunkSize,
                    dzChunkSize: this.options.chunkSize,
                    dzFilename: chunk.file.name,
                  
                };
            }
        },
        /*
    chunksUploaded: function(file,done){
          // NOT SURE WHAT THIS IS FOR
       
          done();
        },
          */      
  init: function() {
    var myAwesomeDropzone = this;
    var itemsToRemove = [];
    var totalsize = 0;
    var totalsizeFlag = false;
    var countImages = 0;
    var uploadedFiles = []; 
    
    this.on("success", function(file, response) {
        
           var fileData = []; 

           if(file.status == 'success'){
                countImages++;
                fileData = JSON.parse(file.xhr.response);
                uploadedFiles.push(fileData);
                if (countImages == myAwesomeDropzone.files.length){
                    
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        type: "POST",
                        data: {uploadedFiles},
    
                        url: "/gallery/save-album",
                        
                        success: function () {
                            // Must call done() if successful
                          //  done();
                        },
                        error: function (msg) {
                           
                        }
                    });
                }
            }

**Comment by bgmastermind** [comment]
Does not really help, you, but my advise is, do not chunk your files. Absolutely no benefit for files under 100mb. Really not worth the effort especially for pictures and other small files. For the shared hosting uploading parameters can be adjusted and you can make it work there it normal upload. If you have some sort of special hosting that does not allow that (must be very rare) just change it. Plenty of offers.

**Comment by pionl** [comment]
Sorry for the inconvenience. I'm using base Dropzone setup which copies the same docs from Drozpzone. I would not recommend to change `params: function (files, xhr, chunk)` which definitely changes the structure of the request. I would definitely use different method to "inject" additional data.
