### ISSUE TITLE
[Upgrade] Support for 5.4

### ISSUE THREAD

**Issue by pionl** [pionl/laravel-chunk-upload#6]
Test the 5.4 version with this package. By the upgrade guid should be OK.

**Comment by RAZORzdenko** [comment]
Any news on 5.4 upgrade or ETA?

**Comment by pionl** [comment]
@RAZORzdenko Hi, will check today. Will let you know

**Comment by pionl** [comment]
The `v1.0.0` version supports 5.4. No upgrade or change required. Works perfectly on fresh install. I've also created an [example project](https://github.com/pionl/laravel-chunk-upload-example).

Thanks
