### ISSUE TITLE
Type error between Illuminate\Http\UploadedFile and Symfony\Component\HttpFoundation\File\UploadedFile

### ISSUE THREAD

**Issue by nsiksnys** [pionl/laravel-chunk-upload#60]
Hello everyone,
I'm using resumable.js in a Laravel 5.1 project, but the upload always fails right at the first attempt with this error message.

```
FatalThrowableError in ParallelSave.php line 40: Type error: Argument 1 passed to Pion\Laravel\ChunkUpload\Save\ParallelSave::__construct() must be an instance of Illuminate\Http\UploadedFile, instance of Symfony\Component\HttpFoundation\File\UploadedFile given, called in /var/www/html/myProject/vendor/pion/laravel-chunk-upload/src/Handler/Traits/HandleParallelUploadTrait.php on line 29
```

This is how I create the resumable object
```
 var resumable = new Resumable({
        target:"{{route('backend.resumable')}}",
        chunkSize: 1*1024*1024,
        testChunks:false,
        simultaneousUploads:1,
        headers:{
            'X-CSRF-Token' :"{{ csrf_token() }}"
        },
        query:{
            _token : "{{ csrf_token() }}"
        }
    });
```
I updated all the dependencies and tried again, but the error persists.
Has anyone faced an error like this before?
Thanks.

**Comment by pionl** [comment]
It seems that 5.1 project is not supported because the object that Laravel passes is different.

You can remove the `UploadFile` type hint   from `HandleParallelUploadTrait:29` and give it try. Let me know if all function works. Thank you

**Comment by pionl** [comment]
Laravel 5.1 is not support anymore -- very complicated to make a integration test.
