### ISSUE TITLE
link to view of resumablejs return 404 

### ISSUE THREAD

**Issue by shsaleh** [pionl/laravel-chunk-upload#66]
hi 
please check  link of resumable js blade file.
sorry can't speak english good.
thanks

https://github.com/pionl/laravel-chunk-upload-example/blob/master/resources/views/example/resumable.js.blade.php

**Comment by aleks365** [comment]
https://github.com/pionl/laravel-chunk-upload-example/blob/master/resources/views/example/resumable.blade.php

**Comment by cawecoy** [comment]
I guess it was moved to https://github.com/pionl/laravel-chunk-upload-example/blob/master/example/resources/views/example/resumable.blade.php
