### ISSUE TITLE
only saves last chunk to google drive on linux system.

### ISSUE THREAD

**Issue by 0Archish0** [pionl/laravel-chunk-upload#74]
When i am uploading few  WAV files only last chunk of those files get uploaded to google drive, i have tried many wav, mp3 and other files but i am having issue with few files. Also when i try to test same files on my local machine everything works fine. but facing issue on my dev and live server.

I am using latest version `1.2.9`

this is my  `config` (same for all 3 environment )

```
"chunk" => [
        // setup for the chunk naming setup to ensure same name upload at same time
        "name" => [
            "use" => [
                "session" => false, // should the chunk name use the session id? The uploader must send cookie!,
                "browser" => true // instead of session we can use the ip and browser?
            ]
        ]
    ]
```

i am using windows + nginx on local, And linux + apache for dev and live.

**Comment by pionl** [comment]
Hi @0Archish0 , what JS library do you use?

Also I've fixed a bug and added a support for Laravel 7 in [v1.4.0]( https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.4.0)

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).
Thank you for your patience.
