### ISSUE TITLE
Laravel 5.3: on last chunks upload getting error

### ISSUE THREAD

**Issue by kajem** [pionl/laravel-chunk-upload#77]
I am getting the below error for last chunk when calling below line.
``$receiver->receive()``
I have lost last two days with this error. Can anyone please help me to get rid of this error
``BadMethodCallException in PluggableTrait.php line 90:
Call to undefined method League\Flysystem\Filesystem::path
``

**Comment by nerg4l** [comment]
Can you share the whole stack trace and which version of `laravel-chunk-upload` you use?

**Comment by kajem** [comment]
@nerg4l I am using version 1.2  "pion/laravel-chunk-upload": "^1.2". 
For the last chunk its try to build full file from the chunks and its getting the above error.

**Comment by kajem** [comment]
Yes, I was path method not having issue. I have changed he getAbsolutePath() method of ChunkFile to return storage_path(). '/app/'.$this->path. Now it is fixed.

**Comment by rosariogueli** [comment]
Hi guys, I was struggling with this a couple of days too and Indeed that was the issue. Howerver, I've just updated my package thinking that it would have this fix, but looks like it hasn't been committed yet?

**Comment by rosariogueli** [comment]
> @nerg4l Yes, I was path method not having issue. I have changed he getAbsolutePath() method of ChunkFile to return storage_path(). '/app/'.$this->path. Now it is fixed.

Hi guys, I was struggling with this a couple of days too and Indeed that was the issue. However, I've just updated my package thinking that it would have your fix included, but looks like it hasn't been committed yet? 

ps: your fix gives my the following error: 
`Call to undefined method League\Flysystem\Filesystem::getPathPrefix`

I've fixed it by replacing the line with the following: 
```
public function getAbsolutePath()
{
    // Original code: 
    // return $this->storage->disk()->path($this->path);

    // Your fix:           
    // return $this->storage->disk()->getPathPrefix().$this->path;

    // What worked for me: 
    return $this->storage->disk()->getDriver()->getAdapter()->getPathPrefix().$this->path;
}
```
