### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by TheFrankman** [pionl/laravel-chunk-upload#79]
Hello There,

Any chance of adding laravel 6.* support ? 

Thanks.

**Comment by TheFrankman** [comment]
@pionl - I have submitted a pull request to update composer.json to allow laravel v6 and also fixed a couple of issues that I came across. This is unlikely to be all of the issues, but chunking with parallel save works. https://github.com/pionl/laravel-chunk-upload/pull/80

**Comment by TheFrankman** [comment]
@pionl - any chance you have had a look at this yet ?

**Comment by Kladislav** [comment]
@pionl - very **important** issue

**Comment by TheFrankman** [comment]
@Kladislav - My un-merged pull request resolved all issues I could find : https://github.com/pionl/laravel-chunk-upload/pull/80

**Comment by Kladislav** [comment]
@TheFrankman yes, i already forked it. :wink:

**Comment by paulm17** [comment]
Unfortunately it's not as simple as getting composer up and running with a private key.  Been at it for 10 mins and keeps asking me for a token.  I give up lol.

Can someone please fork this, make changes and make it public?

Or @pionl are you awake mate?  We would all appreciate if you can take @TheFrankman changes and update the repo.

**Comment by Kladislav** [comment]
@paulm17 https://packagist.org/packages/kladislav/laravel-chunk-upload

**Comment by pionl** [comment]
Sorry guys, had been to busy for GitHub, all merged -- I've will try to find more and resolve all issues and PRS.

PS: @paulm17 If you have your own changes and "overwrite" the packages entry, use the `repositories`. I do it all the time (instead of version I use specific commit): https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

**Comment by paulm17** [comment]
@pionl Great news and many thanks for your continued work.

I finally worked out how to use packagist, so it's all good.
