### ISSUE TITLE
react component

### ISSUE THREAD

**Issue by esmmusavi** [pionl/laravel-chunk-upload#81]
Hi.
I need react component for uploading?

**Comment by nerg4l** [comment]
No. You just need to use one of the libraries listed in the [Usage section](https://github.com/pionl/laravel-chunk-upload/blob/master/readme.md#usage) of the [README.md](https://github.com/pionl/laravel-chunk-upload/blob/master/readme.md).

**Comment by pionl** [comment]
@esmmusavi Feel free to find a library that you like and implement a handler.

Thanks @nerg4l
