### ISSUE TITLE
Support for ngx-uploadx

### ISSUE THREAD

**Issue by Nico205** [pionl/laravel-chunk-upload#82]
Hello,

I've tried to implement this server-side and use [ngx-uploadx](https://github.com/kukhariev/ngx-uploadx) on the client side (Angular 7.x).

However, I always get status code = 500 responses saying "UploadMissingFileException" (using the controller provided in the example code repository).

The request sent to the server just contains this as payload:
`{"name":"file.mp3","mimeType":"","size":96609,"lastModified":1569084371758}`.

Also, those headers are set: `
x-upload-content-length: 96609
x-upload-content-type:`

Any idea why this isn't working?

Friendly Regards
Nico

**Comment by pionl** [comment]
Whats your` input[name]`? The `UploadMissingFileException` is thrown if the file is not sent (the example uses `file`).

**Comment by closca** [comment]
@Nico205 you have to provide your on `uploaderClass`
Check here https://github.com/kukhariev/ngx-uploadx/tree/2ae0784858226d1cae9aeb11206a457e02227f9e/uploader-examples
I used the multipart one and is working ok.

**Comment by Nico205** [comment]
Hello,

thanks for the replies. I've managed to modify the code on both sides to get this working fine!

Friendly Regards
Nico

**Comment by closca** [comment]
@Nico205 actually I was wrong. Using multipart is not what I need (not chunking). Have you managed to use it with ngx-upload and have chunkes?

**Comment by pionl** [comment]
HI @Nico205 can u share the code for others? :)

**Comment by Nico205** [comment]
Hey,
I'm not using this in combination with laravel-chunk-upload. I've switched to upload files directly to S3 using signed URLs.

Friendly Regards
Nico
