### ISSUE TITLE
There is no functionality for testing chunks?

### ISSUE THREAD

**Issue by eroslover** [pionl/laravel-chunk-upload#88]
Hi. Am I correct that this package doesn't have functionality for testing chunks when you use Resumable.js library?

**Comment by rycks** [comment]
Hello eroslover, there is a solution here: https://github.com/pionl/laravel-chunk-upload/issues/10#issuecomment-448615836

**Comment by pionl** [comment]
The package at this moment does not provide any controllers so you can implement your own check. If more people needs it there could be a class that would handle it (or provide default routes for it).
