### ISSUE TITLE
Readme issue - Usage with multiple files in one Request does not have $receiver defined

### ISSUE THREAD

**Issue by Chinese1904** [pionl/laravel-chunk-upload#9]
I have been playing with your package and since I am trying to figure everything out I am following the instructions for the multiple files upload in one request.

In your readme $receiver is not defined or am I missing anything?

**Comment by pionl** [comment]
Hi @Chinese1904 , sorry for the missing docs - bad merge on my side.

You can construct the the `FileReceiver` with a UploadFile object instead of passing an index in request.

```php
    // Loop sent files
    foreach ($files as $file) {
        // Instead of passing the index name, pass the UploadFile object from the $files array we are looping
        
        // Create the file receiver via dynamic handler
        $receiver = new FileReceiver($file, $request, HandlerFactory::classFromRequest($request));
        // or via static handler usage
        $receiver = new FileReceiver($file, $request, ContentRangeUploadHandler::class);
        
```
