### ISSUE TITLE
L7

### ISSUE THREAD

**Issue by ekandreas** [pionl/laravel-chunk-upload#90]
Hey!
Laravel 7 is out...

**Comment by MaximeCarburant** [comment]
Up !
Can we have an update for that ? 
Need this :)

**Comment by ekandreas** [comment]
I'm preparing to replace the package due to lack of L7 support.

**Comment by pionl** [comment]
@ekandreas Have you tried it by forking? Is it working or not? At this moment I've tested it.

**Comment by hamedgasemi200** [comment]
Please do something about Laravel 7. I really need this package.

**Comment by hamedgasemi200** [comment]
@pionl Please do something about Laravel 7. I really need this package.

**Comment by MarioOlivera** [comment]
I hope it updates soon, it's a great package

**Comment by mikaelprag** [comment]
There is a PR #89 and it seems to be pretty trivial. Are there other maintained options that anyone know about?

**Comment by basementcloud** [comment]
> There is a PR #89 and it seems to be pretty trivial. Are there other maintained options that anyone know about?

I found this one. Looks like it's recently forked and updated.
https://github.com/Kladislav/laravel-chunk-upload
https://packagist.org/packages/kladislav/laravel-chunk-upload

**Comment by pionl** [comment]
There was another issue with Laravel 7 (symfony changed UploadedFile constructor).

Fixed a bug and added a support for Laravel 7 in [v1.4.0]( https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.4.0)

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).

If you created a packagist entry please mark it as deprecated (in favor of this package) or delete it - it can confuse people. 

Thank you for your patience.
