### ISSUE TITLE
Not For laravel 7

### ISSUE THREAD

**Issue by goartisans** [pionl/laravel-chunk-upload#95]
This package is not installing on laravel 7. Can you please make it for laravel 7 also

**Comment by nerg4l** [comment]
#89 Is a PR which wants to address this issue. Unfortunately, the maintainer of this package is rarely active lately. You have to wait, fork it or look for a fork which is available on packagist and has the fix.

**Comment by tbclla** [comment]
To add to @nerg4l's answer:

Hopefully this package will be updated soon and you'll only need a temporary solution, so if you don't want to search for and include someone else's fork on packagist as a dependency, go the VCS route:

1. Fork this package and create a new branch called, for example, **dev-laravel7**. 
2. Make the changes from the above mentioned PR #89 and commit to the new branch.
3. In your project's composer.json, add you fork as a vcs repository
```
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/yourname/laravel-chunk-upload"
  }
],
```
4. Also in your project's composer.json, require this package `pion/laravel-chunk-upload` as usual, but use your fork's updated branch as version constraint.
```

"require": {
  "pion/laravel-chunk-upload": "dev-laravel7"
},
```
5. run `composer update`

Once this package get updated and is compatible with Laravel 7, you can simply remove your fork from your project's composer.json and update the version constraint.

**Comment by lpsBetty** [comment]
@tbclla I am using @romanzipp's fork with this in composer.json

```
    "repositories": [
        {
            "url": "https://github.com/romanzipp/laravel-chunk-upload",
            "type": "vcs"
        }
    ],
    "require": {
        "pionl/laravel-chunk-upload": "dev-laravel-7"
```

still i get this error:

```
  Problem 1
    - The requested package pionl/laravel-chunk-upload could not be found in any version, there may be a typo in the package name.
```

**Comment by romanzipp** [comment]
I've registered the repository with `"type": "git"`, not sure if this behaves differently than `vcs`

**Comment by lpsBetty** [comment]
@tbclla @romanzipp ah sorry, i was being stupid.. it is `pion/laravel-chunk-upload` not `pionl` - got confused by the github name

**Comment by michealmueller** [comment]
so by make the changes in the PR it does in fact work for laravel 7 or no?

**Comment by lpsBetty** [comment]
@michealmueller yes it does work

**Comment by MaximMonin** [comment]
copy current compose.json
add
"repositories": [
        {
            "url": "https://github.com/romanzipp/laravel-chunk-upload.git",
            "type": "git"
        }
    ],
    "require": {
        "pion/laravel-chunk-upload": "dev-laravel-7"
   }
install:
COPY composer.json /app
RUN composer update && php artisan vendor:publish --provider="Pion\Laravel\ChunkUpload\Providers\ChunkUploadServiceProvider"

**Comment by pionl** [comment]
Fixed a bug and added a support for Laravel 7 in [v1.4.0]( https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.4.0)

🎉 Finally a release for Laravel 7 support
⛑ Finally I've fixed problems with chunks (Dropzone/Resumable.js with parallel upload). 
👍 Also I've found a solution how to get file data after upload for a Dropzone. Check [WIKI](https://github.com/pionl/laravel-chunk-upload/wiki/Dropzone#get-final-response-data).

If you created a packagist entry please mark it as deprecated (in favor of this package) or delete it - it can confuse people. 

Thank you for your patience.
